version: '3.4'

services:
  services.customerservice:
    image: ${DOCKER_REGISTRY-}servicescustomerservice
    build:
      context: .
      dockerfile: Services.CustomerService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__CUSTSVC: "" 
   
  services.customerservice.testcases:
    image: ${DOCKER_REGISTRY-}servicescustomerservicetestcases
    build:
      context: .
      dockerfile: Services.CustomerService.TestCases/Dockerfile

